### ISSUE TITLE
Document default git reset --hard?

### ISSUE THREAD

**Issue by carzacc** [arighi/kernelcraft#1]
Shouldn't the fact that, with default options, the tool will run `git reset --hard HEAD` as its first step be documented?

Maybe it's just me, but I didn't expect that would happen and lost a bunch of changes I had staged and was trying to test before committing.

**Comment by arighi** [comment]
@carzacc sorry about your lost changes... Maybe we should just error if we detect changes that are not committed, instead of implicitly running `git reset --hard`. And also provide a `--force` option that would implicitly run the `reset --hard`.

Alternatively, we could just accept uncommitted changes if we build locally and use the logic above only if `--build-host` is used. What do you think?

**Comment by carzacc** [comment]
The second option (only worrying about uncommitted changes for remote builds, and in that case resetting only with some form of user consent) certainly makes a lot of sense, and it would save the user a (potentially soon-to-be amended) commit.

I would argue, though, that it's unnecessary in this case: that logic (erroring on unstaged changes, resetting instead with --force) applied consistently in every usage mode seems enough to me, the effort required of the user to just commit the changes wouldn't amount to much and the simplicity and consistency of the logic would be a benefit in itself.

**Comment by carzacc** [comment]
(on a light-hearted note about the lost changes, there is nothing to worry about if prof. Valente accepts "kernelcraft ate my homework" as an excuse for not having done what he asked)

**Comment by arighi** [comment]
> I would argue, though, that it's unnecessary in this case: that logic (erroring on unstaged changes, resetting instead with --force) applied consistently in every usage mode seems enough to me, the effort required of the user to just commit the changes wouldn't amount to much and the simplicity and consistency of the logic would be a benefit in itself.

True, but we may actually want to use kc to run multiple test builds before creating the actual commit (even if it's a "fake" commit). Considering that the whole point of this tool is to speed up kernel development / testing it seems odd to force the user to always create a commit, instead of just allowing to test local uncommitted changes.

This doesn't apply of course if you want to do a remote build, because we rely on git push to sync the source code remotely, so in that case the only option is to commit all your local changes, so in this case we should error if there are local changes (and provide a `--force` so that the user can explicitly say "I don't care about my local changes, just drop them").

**Comment by arighi** [comment]
> (on a light-hearted note about the lost changes, there is nothing to worry about if prof. Valente accepts "kernelcraft ate my homework" as an excuse for not getting stuff done)

Change that to "kernelcraft ate my homework, so I filed a bug upstream and contributed to fix the issue" and report it to prof. Valente. This sounds like a nice way to turn a bug into a feature. ;)
